import type { AllowedCategory, AllowedItem } from '../types/content'

export const ALLOWED_CATEGORIES: { id: AllowedCategory; label: string; emoji: string }[] = [
  { id: 'fish', label: 'דגים ופירות ים', emoji: '🍣' },
  { id: 'cheese', label: 'גבינות', emoji: '🧀' },
  { id: 'meat', label: 'בשר', emoji: '🥩' },
  { id: 'drinks', label: 'שתייה', emoji: '☕' },
  { id: 'eggs', label: 'ביצים ומוצרים', emoji: '🥚' },
  { id: 'exercise', label: 'פעילות גופנית', emoji: '🏋️' },
  { id: 'travel', label: 'נסיעות', emoji: '✈️' },
  { id: 'beauty', label: 'טיפולים וקוסמטיקה', emoji: '💅' },
  { id: 'medicine', label: 'תרופות', emoji: '💊' },
  { id: 'other', label: 'אחר', emoji: '❤️' },
]

export const allowedItems: AllowedItem[] = [
  // 🍣 דגים ופירות ים
  {
    category: 'fish',
    verdict: 'red',
    item: 'סושי נא',
    emoji: '🍣',
    short: 'סיכון לליסטריה וטפילים',
    aba_translation: 'הסשימי נשאר לאחרי הלידה.',
    dad_action: 'כשיוצאים לאוכל יפני — הזמן לה מבושל. תגיד שבדקת.',
  },
  {
    category: 'fish',
    verdict: 'green',
    item: 'סושי מבושל',
    emoji: '🍣',
    short: 'דג מבושל היטב — בסדר גמור',
    aba_translation: 'רול קליפורניה? תזמין בלי דאגה.',
    dad_action: 'תזמין בלי היסוס. אין צורך לשאול את המלצר שאלות מיותרות.',
  },
  {
    category: 'fish',
    verdict: 'yellow',
    item: 'טונה (שימורים)',
    emoji: '🐟',
    short: 'עד כ-140 גרם בשבוע',
    aba_translation: 'קצת טונה — בסדר. קנטינה של טונה — לא.',
    dad_action: 'תספור איתה כמה פעמים בשבוע. לא לשים לב זה לא עוזר.',
  },
  {
    category: 'fish',
    verdict: 'green',
    item: 'סלמון מבושל',
    emoji: '🐟',
    short: 'אומגה 3 חשוב להתפתחות',
    aba_translation: 'מהדגים הכי טובים בהריון. תבשל היטב.',
    dad_action: 'תבשל לה סלמון פעם בשבוע. זה גם טעים לך.',
  },
  {
    category: 'fish',
    verdict: 'green',
    item: 'חומוס',
    emoji: '🥙',
    short: 'מזון בטוח ומזין',
    aba_translation: 'תמלא קערה. אין שום סיבה לדאוג.',
    dad_action: 'תביא לה קערה בלי לשאול. תמיד עובד.',
  },
  {
    category: 'fish',
    verdict: 'red',
    item: 'דג חרב / כריש',
    emoji: '🦈',
    short: 'כספית גבוהה מדי',
    aba_translation: 'דג גדול = כספית גדולה. תדלג.',
    dad_action: 'בתפריט דגים — תדלג על הגדולים בשבילה.',
  },

  // 🧀 גבינות
  {
    category: 'cheese',
    verdict: 'green',
    item: 'גבינה לבנה מפוסטרת',
    emoji: '🧀',
    short: 'פסטוריזציה = בטוח',
    aba_translation: 'תבדוק שכתוב "מפוסטר" ותאכל בשקט.',
    dad_action: 'אין מה לבדוק. תמרח בשקט.',
  },
  {
    category: 'cheese',
    verdict: 'green',
    item: 'גבינה צהובה',
    emoji: '🧀',
    short: 'מפוסטרת כמעט תמיד',
    aba_translation: 'סנדוויץ׳ גבינה צהובה — בלי חשש.',
    dad_action: 'סנדוויץ׳ רגיל. בלי דרמה.',
  },
  {
    category: 'cheese',
    verdict: 'yellow',
    item: 'גבינת עיזים רכה',
    emoji: '🧀',
    short: 'רק אם מפוסטרת',
    aba_translation: 'תבדוק תווית. לא מפוסטר — לא עכשיו.',
    dad_action: 'תסתכל על התווית לפני שאתה מגיש לה.',
  },
  {
    category: 'cheese',
    verdict: 'yellow',
    item: 'בולגרית',
    emoji: '🧀',
    short: 'רק אם מפוסטרת',
    aba_translation: 'תבדוק את התווית. פסטוריזציה — כן. לא — לא.',
    dad_action: 'אותו סיפור — תבדוק שכתוב מפוסטר.',
  },
  {
    category: 'cheese',
    verdict: 'red',
    item: 'ברי / קממבר',
    emoji: '🧀',
    short: 'סיכון לליסטריה',
    aba_translation: 'גבינות עובש רכות נשארות למועד אחר.',
    dad_action: 'בפגישת חברים — תזיז לה את הצלחת הזו.',
  },
  {
    category: 'cheese',
    verdict: 'green',
    item: 'מוצרלה',
    emoji: '🧀',
    short: 'מפוסטרת ובטוחה',
    aba_translation: 'פיצה עם מוצרלה — תיהני.',
    dad_action: 'פיצה משפחתית — בלי לחשוב פעמיים.',
  },

  // 🥩 בשר
  {
    category: 'meat',
    verdict: 'green',
    item: 'בשר מבושל היטב',
    emoji: '🍖',
    short: 'בישול מלא הורג חיידקים וטפילים',
    aba_translation: 'עשוי היטב, לא ורוד באמצע — בסדר.',
    dad_action: 'תוודא שהסטייק שלה עשוי היטב, לא רק שלך.',
  },
  {
    category: 'meat',
    verdict: 'red',
    item: 'בשר נא / טרטר',
    emoji: '🥩',
    short: 'סיכון לטוקסופלזמה',
    aba_translation: 'הסטייק הוורוד באמצע — לא הפעם.',
    dad_action: 'כשמזמינים בשר — תבקש בשבילה עשוי היטב, גם אם היא לא ביקשה.',
  },
  {
    category: 'meat',
    verdict: 'yellow',
    item: 'נקניקיות חמות',
    emoji: '🌭',
    short: 'רק כשחמות ומאודות היטב',
    aba_translation: 'חמות עד קיטור — כן. פושרות מהמקרר — לא.',
    dad_action: 'תחמם עד שמעשן ממש. לא פושר מהמקרר.',
  },
  {
    category: 'meat',
    verdict: 'yellow',
    item: 'נקניק / שרקוטרי',
    emoji: '🥓',
    short: 'מחומם היטב בסדר',
    aba_translation: 'תחמם עד שמעשן. אז זה בטוח.',
    dad_action: 'כריך נקניק — תחמם קודם בטוסטר.',
  },
  {
    category: 'meat',
    verdict: 'red',
    item: 'כבד',
    emoji: '🍖',
    short: 'ויטמין A גבוה מדי',
    aba_translation: 'כבד קצוץ נשאר על המדף הזה.',
    dad_action: 'כשההורים מגישים כבד קצוץ בערב חג — תסביר בעדינות שהיא מדלגת.',
  },

  // ☕ שתייה
  {
    category: 'drinks',
    verdict: 'yellow',
    item: 'קפה',
    emoji: '☕',
    short: 'עד כ-200 מ"ג קפאין ביום',
    aba_translation: 'אפשר. פשוט לא להפוך את ההריון לתחנת דלק של אספרסו.',
    dad_action: 'היא שותה יותר מכוס? לא לדון. לשים את הכוס בצד.',
  },
  {
    category: 'drinks',
    verdict: 'yellow',
    item: 'תה',
    emoji: '🍵',
    short: 'גם הוא נחשב במכסת הקפאין',
    aba_translation: 'תה זה גם קפאין. תספרי כוסות.',
    dad_action: 'תזכיר לה שגם תה נספר במכסה, לא רק קפה.',
  },
  {
    category: 'drinks',
    verdict: 'yellow',
    item: 'תה צמחים',
    emoji: '🌿',
    short: 'תלוי בסוג הצמח',
    aba_translation: 'לא כל צמח בטוח. תבדקי איזה תה זה.',
    dad_action: 'לפני שאתה מכין לה תה חדש — תבדוק על מה זה עשוי.',
  },
  {
    category: 'drinks',
    verdict: 'red',
    item: 'אלכוהול',
    emoji: '🍷',
    short: 'אין כמות בטוחה מוכחת',
    aba_translation: 'אין כמות בטוחה. זה הגבול הכי ברור שיש.',
    dad_action: 'אל תשתה לידה. לא בגלל שאסור — כי זה לא הזמן.',
  },
  {
    category: 'drinks',
    verdict: 'red',
    item: 'מיץ טבעי לא מפוסטר',
    emoji: '🧃',
    short: 'סיכון לחיידקים',
    aba_translation: 'מיץ סחוט טרי בדוכן — לדלג הפעם.',
    dad_action: 'בדוכן בשוק — תבדוק אם המיץ מפוסטר לפני שאתה מזמין לה.',
  },
  {
    category: 'drinks',
    verdict: 'green',
    item: 'סודה / שתייה מוגזת',
    emoji: '🥤',
    short: 'בסדר בכמות מתונה',
    aba_translation: 'קולה קרה מדי פעם — לא קורה כלום.',
    dad_action: 'אין צורך להרגיש רע על קולה קרה.',
  },

  // 🥚 ביצים ומוצרים
  {
    category: 'eggs',
    verdict: 'green',
    item: 'ביצה מבושלת',
    emoji: '🥚',
    short: 'בישול מלא = בטוח',
    aba_translation: 'קשה לגמרי — תאכלי כמה שבא לך.',
    dad_action: 'תבשל לה קשה בלי לשאול.',
  },
  {
    category: 'eggs',
    verdict: 'red',
    item: 'ביצה חיה / רכה',
    emoji: '🥚',
    short: 'סיכון לסלמונלה',
    aba_translation: 'החביתה עין נשארת עם חלמון מוצק.',
    dad_action: 'חביתת עין — תוודא שהחלמון מוצק לפני שאתה מגיש.',
  },
  {
    category: 'eggs',
    verdict: 'green',
    item: 'מיונז מסחרי',
    emoji: '🥫',
    short: 'עשוי מביצים מפוסטרות',
    aba_translation: 'מהמדף — בסדר. מהמטבח שלכם — תבדקי מה בפנים.',
    dad_action: 'מהצנצנת — בסדר גמור. אין מה לבדוק.',
  },
  {
    category: 'eggs',
    verdict: 'red',
    item: 'מיונז ביתי',
    emoji: '🥣',
    short: 'ביצה גולמית לא מפוסטרת',
    aba_translation: 'המתכון הביתי הזה — לדחות בכמה חודשים.',
    dad_action: 'המתכון הביתי שלך — תדחה אותו לאחרי הלידה.',
  },

  // 🏋️ פעילות גופנית
  {
    category: 'exercise',
    verdict: 'green',
    item: 'הליכה',
    emoji: '🚶',
    short: 'מומלצת לאורך כל ההריון',
    aba_translation: 'הכי פשוט. הכי בטוח. תלכו יחד.',
    dad_action: 'הצע ללכת איתה. גם לך יעשה טוב.',
  },
  {
    category: 'exercise',
    verdict: 'green',
    item: 'שחייה',
    emoji: '🏊',
    short: 'אחת הפעילויות הכי מומלצות',
    aba_translation: 'הפעילות הכי טובה שיש. ברצינות.',
    dad_action: 'תבדוק שיש בריכה נגישה קרוב לבית.',
  },
  {
    category: 'exercise',
    verdict: 'green',
    item: 'יוגה הריון',
    emoji: '🧘',
    short: 'בנויה במיוחד להריון',
    aba_translation: 'מדריך מוסמך להריון — כן. סתם שיעור יוגה — תבדקי.',
    dad_action: 'תעזור לה למצוא מדריך שמוסמך ספציפית להריון.',
  },
  {
    category: 'exercise',
    verdict: 'yellow',
    item: 'ריצה (אם הייתה לפני)',
    emoji: '🏃',
    short: 'להתייעץ ולהאט קצב',
    aba_translation: 'אם רצה לפני — בדרך כלל אפשר להמשיך. שאלה לרופא.',
    dad_action: 'אם רצה לפני — תעודד להמשיך בקצב מתון, לא לעצור בבת אחת.',
  },
  {
    category: 'exercise',
    verdict: 'yellow',
    item: 'אימוני כוח קלים',
    emoji: '🏋️',
    short: 'משקל מתון, בלי לשכב על הגב',
    aba_translation: 'ללכת. לא להרים ספסל.',
    dad_action: 'תזכיר לה: משקל קל, לא לשכב על הגב.',
  },
  {
    category: 'exercise',
    verdict: 'red',
    item: 'ספורט מגע',
    emoji: '🥊',
    short: 'סיכון למכה בבטן',
    aba_translation: 'הכפפות נשארות בארון עד אחרי.',
    dad_action: 'אם היא מתגעגעת לכדורגל — תציע לצפות מהצד.',
  },
  {
    category: 'exercise',
    verdict: 'red',
    item: 'צלילה',
    emoji: '🤿',
    short: 'סיכון לעובר מלחץ',
    aba_translation: 'העולם התת-ימי מחכה. עוד כמה חודשים.',
    dad_action: 'הציוד נשאר בארון. תזכיר לה שזה זמני.',
  },

  // ✈️ נסיעות
  {
    category: 'travel',
    verdict: 'yellow',
    item: 'טיסה עד שבוע 36',
    emoji: '✈️',
    short: 'לרוב בסדר, עם אישור רופא',
    aba_translation: 'תבדוק עם חברת התעופה. הם לפעמים דורשים אישור רופא.',
    dad_action: 'תבדוק מראש עם חברת התעופה אם צריך אישור רופא.',
  },
  {
    category: 'travel',
    verdict: 'red',
    item: 'טיסה אחרי שבוע 36',
    emoji: '✈️',
    short: 'קרוב מדי ללידה',
    aba_translation: 'אחרי שבוע 36 — נשארים על הקרקע.',
    dad_action: 'אם מתכננים טיול — תזיז אותו לפני שבוע 36.',
  },
  {
    category: 'travel',
    verdict: 'yellow',
    item: 'נסיעה ארוכה ברכב',
    emoji: '🚗',
    short: 'עצירות תכופות מומלצות',
    aba_translation: 'כל שעתיים — עצירה למתוח רגליים.',
    dad_action: 'תתכנן עצירות מראש. אל תחכה שתבקש.',
  },
  {
    category: 'travel',
    verdict: 'yellow',
    item: 'הרים גבוהים (+2500 מ׳)',
    emoji: '🏔️',
    short: 'תלוי בגובה ומצב בריאותי',
    aba_translation: 'טרק בהימלאיה — שאלה לרופא קודם.',
    dad_action: 'לפני טיול בהרים — תשאל רופא, לא רק Waze.',
  },

  // 💅 טיפולים וקוסמטיקה
  {
    category: 'beauty',
    verdict: 'yellow',
    item: 'צביעת שיער (טרימסטר 2+)',
    emoji: '💇',
    short: 'טרימסטר שני ושלישי — לרוב בסדר',
    aba_translation: 'טרימסטר ראשון — להיוועץ. אחרי זה — בדרך כלל אפשר.',
    dad_action: 'תזכיר לה שבטרימסטר שני זה כבר בסדר.',
  },
  {
    category: 'beauty',
    verdict: 'red',
    item: "ג'קוזי / אמבטיה חמה",
    emoji: '🛁',
    short: 'טמפרטורה גבוהה — לא מומלצת',
    aba_translation: 'חם מדי. לא עכשיו.',
    dad_action: 'אם היא מציעה ספא — הצע אלטרנטיבה. עיסוי, לא חום.',
  },
  {
    category: 'beauty',
    verdict: 'green',
    item: 'עיסוי הריון',
    emoji: '💆',
    short: 'אצל מעסה מוסמך להריון',
    aba_translation: 'מעסה שיודע מה הוא עושה — כן בבקשה.',
    dad_action: 'תזמין לה תור אצל מעסה שמתמחה בהריון.',
  },
  {
    category: 'beauty',
    verdict: 'yellow',
    item: 'עיסוי רגיל',
    emoji: '💆',
    short: 'עדיף מעסה מוסמך להריון',
    aba_translation: 'תגידי שאת בהריון לפני שמתחילים.',
    dad_action: 'תזכיר לה להגיד שהיא בהריון כשקובעים תור.',
  },
  {
    category: 'beauty',
    verdict: 'red',
    item: 'ספא / סאונה',
    emoji: '🧖',
    short: 'חום גבוה מסוכן',
    aba_translation: 'החום הגבוה נשאר בחוץ הפעם.',
    dad_action: 'החום הגבוה מסוכן. תציע לה בית קפה במקום.',
  },
  {
    category: 'beauty',
    verdict: 'yellow',
    item: 'מניקור',
    emoji: '💅',
    short: 'במקום עם אוורור טוב',
    aba_translation: 'תבחרי מקום מאוורר. שאר הזמן — תיהני.',
    dad_action: 'תבדוק שהמקום מאוורר לפני שאתה קובע תור.',
  },

  // 💊 תרופות
  {
    category: 'medicine',
    verdict: 'yellow',
    item: 'פרצטמול',
    emoji: '💊',
    short: 'במינון נמוך ולפי הצורך',
    aba_translation: 'פרצטמול — בדרך כלל אפשר. כל שאר — שאלה לרופא.',
    dad_action: 'תזכיר לה מינון נמוך, לא לפי הרגל.',
  },
  {
    category: 'medicine',
    verdict: 'red',
    item: 'איבופרופן',
    emoji: '💊',
    short: 'להימנע בטרימסטר 2-3',
    aba_translation: 'האיבופרופן נשאר בארון התרופות.',
    dad_action: 'תוציא אותו מהארון בבית לתקופה הזו.',
  },
  {
    category: 'medicine',
    verdict: 'red',
    item: 'אספירין',
    emoji: '💊',
    short: 'רק לפי הנחיית רופא',
    aba_translation: 'בלי אישור רופא מפורש — לא.',
    dad_action: 'בלי אישור רופא מפורש — לא נותנים.',
  },
  {
    category: 'medicine',
    verdict: 'yellow',
    item: 'אנטיהיסטמינים',
    emoji: '💊',
    short: 'לפי הנחיית רופא',
    aba_translation: 'תשאלי רופא איזה סוג בטוח.',
    dad_action: 'תשאל רופא לפני שאתה מציע לה כדור לאלרגיה.',
  },

  // ❤️ אחר
  {
    category: 'other',
    verdict: 'green',
    item: 'סקס',
    emoji: '❤️',
    short: 'בהריון תקין — לרוב בסדר',
    aba_translation: 'כן — אלא אם הרופא אמר אחרת.',
    dad_action: 'אלא אם הרופא אמר אחרת — הכל כרגיל.',
  },
  {
    category: 'other',
    verdict: 'red',
    item: 'ניקוי ארגז חול',
    emoji: '🐱',
    short: 'סיכון לטוקסופלזמה',
    aba_translation: 'המשימה הזו עוברת אליך. לא משא ומתן.',
    dad_action: 'המשימה עברה אליך. לא לדיון.',
  },
  {
    category: 'other',
    verdict: 'yellow',
    item: 'צבע קירות',
    emoji: '🎨',
    short: 'אוורור טוב, צבע מבוסס-מים',
    aba_translation: 'חלון פתוח, צבע לטקס — בסדר.',
    dad_action: 'תפתח חלון ותבחר צבע לטקס לפני שהיא נכנסת לחדר.',
  },
  {
    category: 'other',
    verdict: 'green',
    item: 'כלי בית',
    emoji: '🧤',
    short: 'כפפות עם חומרי ניקוי חזקים',
    aba_translation: 'תנקי בשקט. רק תשתמשי בכפפות.',
    dad_action: 'תשאיר לה כפפות ליד חומרי הניקוי החזקים.',
  },
]
