import type { SizeComparison } from '../types/content'

const DISCLAIMER =
  'מידה משוערת, מבוססת על ממוצעים רפואיים מקובלים. יכולה להשתנות מעובר לעובר.'

export const sizeComparisons: SizeComparison[] = [
  {
    week: 3,
    size_item: 'נקודה בסוף משפט',
    size_punchline: 'עוד אין מה לראות. תמשיך לגלול.',
    size_value: '',
    size_display: 'עוד לא ניתן למדוד',
    size_disclaimer: DISCLAIMER,
    emoji: '•',
  },
  {
    week: 4,
    size_item: 'גרגר מלח גס',
    size_punchline: 'תתחיל להרגיל את עצמך לסבלנות.',
    size_value: '0.2 ס״מ',
    size_display: 'כ-0.2 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🧂',
  },
  {
    week: 5,
    size_item: 'פול קפה',
    size_punchline: 'הוא לא ישמע על הקפה. עדיין.',
    size_value: '0.3 ס״מ',
    size_display: 'כ-0.3 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '☕',
  },
  {
    week: 6,
    size_item: 'מחק של עיפרון',
    size_punchline: 'אי אפשר למחוק מה שנעשה.',
    size_value: '0.6 ס״מ',
    size_display: 'כ-0.6 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '✏️',
  },
  {
    week: 7,
    size_item: 'סוללת שעון',
    size_punchline: 'קטנה. מפעילה הכל.',
    size_value: '1.3 ס״מ',
    size_display: 'כ-1.3 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🔋',
  },
  {
    week: 8,
    size_item: '10 אגורות',
    size_punchline: 'המטבע המיותר בעולם.',
    size_value: '1.6 ס״מ',
    size_display: 'כ-1.6 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🪙',
  },
  {
    week: 9,
    size_item: 'פקק בירה קורונה',
    size_punchline: 'כן. ממש ככה. תתחיל להאמין.',
    size_value: '2.3 ס״מ',
    size_display: 'כ-2.3 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🍺',
  },
  {
    week: 10,
    size_item: 'כדור פינג פונג',
    size_punchline: 'זה שתמיד דורכים עליו והלך המשחק.',
    size_value: '3.1 ס״מ',
    size_display: 'כ-3.1 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🏓',
  },
  {
    week: 11,
    size_item: 'גלולה למניעת הריון',
    size_punchline: 'מאוחר מדי.',
    size_value: '4.1 ס״מ',
    size_display: 'כ-4.1 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '💊',
  },
  {
    week: 12,
    size_item: 'חפיסת מסטיק Orbit',
    size_punchline: 'תמיד יש אחת בכיס. עד שאין.',
    size_value: '5.4 ס״מ',
    size_display: 'כ-5.4 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🍬',
  },
  {
    week: 13,
    size_item: 'קפסולת נספרסו',
    size_punchline: 'גם היא לא זזה בלי מים.',
    size_value: '7.4 ס״מ',
    size_display: 'כ-7.4 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '☕',
  },
  {
    week: 14,
    size_item: 'כרטיס אשראי',
    size_punchline: 'תתחיל לאהוב את שניהם. אתה תשתמש בהם הרבה.',
    size_value: '8.7 ס״מ',
    size_display: 'כ-8.7 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '💳',
  },
  {
    week: 15,
    size_item: "כוס צ'ייסר",
    size_punchline: 'שתה אותה. זה הזמן האחרון שאתה שותה בלי לספור.',
    size_value: '10.1 ס״מ',
    size_display: 'כ-10.1 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🥃',
  },
  {
    week: 16,
    size_item: 'שלט המזגן',
    size_punchline: 'הדיון על הטמפרטורה בבית עכשיו רשמי.',
    size_value: '11.6 ס״מ',
    size_display: 'כ-11.6 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '📱',
  },
  {
    week: 17,
    size_item: 'קופסת סיגריות',
    size_punchline: 'לא זמן מתאים. גם לך.',
    size_value: '13 ס״מ',
    size_display: 'כ-13 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '📦',
  },
  {
    week: 18,
    size_item: 'קופסת קלפים Bicycle',
    size_punchline: '54 קלפים. הוא מחזיק בכולם.',
    size_value: '14.2 ס״מ',
    size_display: 'כ-14 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🃏',
  },
  {
    week: 19,
    size_item: 'פחית רד בול',
    size_punchline: 'הוא מלא אנרגיה. אתה פחות.',
    size_value: '15.3 ס״מ',
    size_display: 'כ-15.3 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🥤',
  },
  {
    week: 20,
    size_item: 'אייפון 6',
    size_punchline: 'ישן. איטי. עדיין עובד מצוין.',
    size_value: '25.6 ס״מ',
    size_display: 'כ-25.6 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '📱',
  },
  {
    week: 21,
    size_item: 'בלוק גבינה צהובה',
    size_punchline: 'כולם אוהבים. אף אחד לא מודה.',
    size_value: '26.7 ס״מ',
    size_display: 'כ-26.7 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🧀',
  },
  {
    week: 22,
    size_item: 'שלט Xbox',
    size_punchline: 'תיהנה בינתיים.',
    size_value: '27.8 ס״מ',
    size_display: 'כ-27.8 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🎮',
  },
  {
    week: 23,
    size_item: 'שקית במבה',
    size_punchline: 'מלוחה, קראנצ׳ית, כולם אוהבים אותה.',
    size_value: '28.9 ס״מ',
    size_display: 'כ-28.9 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🥜',
  },
  {
    week: 24,
    size_item: 'בקבוק קטשופ Heinz',
    size_punchline: 'לא זזה כמה שתנענע. ואז פתאום הכל בבת אחת.',
    size_value: '30 ס״מ',
    size_display: 'כ-30 ס״מ',
    size_disclaimer: DISCLAIMER,
    emoji: '🍅',
  },
  {
    week: 25,
    size_item: '2 פחיות היינקן',
    size_punchline: 'קרות. כבדות. לא בשבילך עכשיו.',
    size_value: '660 גרם',
    size_display: 'כ-660 גרם',
    size_disclaimer: DISCLAIMER,
    emoji: '🍺',
  },
  {
    week: 26,
    size_item: '3 קופסאות טונה',
    size_punchline: 'חלבון, ברזל, וריח שהיא לא יכולה לסבול.',
    size_value: '760 גרם',
    size_display: 'כ-760 גרם',
    size_disclaimer: DISCLAIMER,
    emoji: '🐟',
  },
  {
    week: 27,
    size_item: 'קילו בשר טחון',
    size_punchline: 'מינוס הקציצה שאכלת.',
    size_value: '875 גרם',
    size_display: 'כ-875 גרם',
    size_disclaimer: DISCLAIMER,
    emoji: '🥩',
  },
  {
    week: 28,
    size_item: 'חבילת קפה Lavazza',
    size_punchline: 'הוא לא צריך עדיין. אתה כבר מאוד צריך.',
    size_value: '1005 גרם',
    size_display: 'כ-1 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '☕',
  },
  {
    week: 29,
    size_item: 'בקבוק שמן מנוע + הפקק',
    size_punchline: 'כבד, חיוני, משמן את כל המנגנון.',
    size_value: '1153 גרם',
    size_display: 'כ-1.15 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '🔧',
  },
  {
    week: 30,
    size_item: '2 חבילות פסטה',
    size_punchline: 'לפני הלידה תבשל. אחרי — תזמין.',
    size_value: '1319 גרם',
    size_display: 'כ-1.3 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '🍝',
  },
  {
    week: 31,
    size_item: 'MacBook Air 13',
    size_punchline: 'כי גם הוא עולה כמו MacBook.',
    size_value: '1502 גרם',
    size_display: 'כ-1.5 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '💻',
  },
  {
    week: 32,
    size_item: 'שישיית בירה חסר אחת',
    size_punchline: 'מישהו כבר התחיל.',
    size_value: '1702 גרם',
    size_display: 'כ-1.7 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '🍺',
  },
  {
    week: 33,
    size_item: 'לאפה שוורמה',
    size_punchline: 'עם כל התוספות — תקנה לאישה דחוף.',
    size_value: '1918 גרם',
    size_display: 'כ-1.9 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '🥙',
  },
  {
    week: 34,
    size_item: 'מקדחה עם סוללה',
    size_punchline: 'סופסוף תשתמש בה.',
    size_value: '2146 גרם',
    size_display: 'כ-2.15 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '🔨',
  },
  {
    week: 35,
    size_item: 'קוקוס שלם',
    size_punchline: 'קשה מבחוץ. מפתיע מבפנים.',
    size_value: '2383 גרם',
    size_display: 'כ-2.4 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '🥥',
  },
  {
    week: 36,
    size_item: "Nintendo Switch + ג'ויסטיק",
    size_punchline: 'תיהנה. לא לאורך זמן.',
    size_value: '2622 גרם',
    size_display: 'כ-2.6 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '🎮',
  },
  {
    week: 37,
    size_item: 'קערת סלט גדולה מלאה',
    size_punchline: 'כן, גם הקערה.',
    size_value: '2859 גרם',
    size_display: 'כ-2.9 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '🥗',
  },
  {
    week: 38,
    size_item: 'תרמיל ילדים ממולא',
    size_punchline: 'כבר ארזת אותו?',
    size_value: '3083 גרם',
    size_display: 'כ-3.1 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '🎒',
  },
  {
    week: 39,
    size_item: '10 קופסאות שימורים',
    size_punchline: 'המלאי שצברת למלחמה הבאה.',
    size_value: '3288 גרם',
    size_display: 'כ-3.3 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '🥫',
  },
  {
    week: 40,
    size_item: 'הוא/היא',
    size_punchline: 'אין מה להוסיף.',
    size_value: '3462 גרם',
    size_display: 'כ-3.5 ק״ג',
    size_disclaimer: DISCLAIMER,
    emoji: '👶',
  },
]
