// 50 עובדות מאומתות ל-"ידעת?" — Aba
// מקורות: Mayo Clinic, ACOG, Cleveland Clinic, PubMed

export type WtfCategory = 'growth' | 'dad' | 'wow' | 'bond'

export interface WtfFact {
  id: string;
  category: WtfCategory;
  factual_text: string;
  aba_line: string;
  week?: number;
  source: string;
}

export const wtfFacts: WtfFact[] = [
  { id:'w3-sex', category:'growth', factual_text:'המין הגנטי נקבע ברגע ההפריה על ידי הזרע.', aba_line:'אתה החלטת ילד או בת. עוד לפני שידעת שאתה אבא.', week:3, source:'ACOG' },
  { id:'w4-hcg', category:'growth', factual_text:'בדיקת הריון מזהה הורמון HCG — לא את הבוטן עצמו.', aba_line:'הבדיקה לא ראתה אותו. היא ראתה את ההורמון. הוא עדיין שקוף.', week:4, source:'Mayo Clinic' },
  { id:'w5-growth', category:'growth', factual_text:'הבוטן גדל פי 10,000 ביחס לגודלו בהפריה תוך השבועות הראשונים.', aba_line:'פי 10,000. שום דבר בטבע לא גדל ככה. כולל הכסף שלך.', week:5, source:'Embryology (Moore)' },
  { id:'w7-neurons', category:'growth', factual_text:'המוח העוברי מייצר מאות אלפי תאי עצב בדקה בשבועות 7-18.', aba_line:'כל דקה — מאות אלפי תאי מוח חדשים. בגוף קטן מאצבעך.', week:7, source:'Purves Neuroscience' },
  { id:'w9-yawn', category:'growth', factual_text:'הבוטן מפהק כבר משבוע 9 — המוח מתרגל רפלקסים.', aba_line:'הוא מפהק. לא כי משעמם לו. כי המוח מתרגל. בשבוע 9.', week:9, source:'Cleveland Clinic' },
  { id:'w9-eyelids', category:'growth', factual_text:'העפעפיים נסגרים בשבוע 9 ונשארים סגורים עד שבוע 28.', aba_line:'19 שבועות עם עיניים סגורות. ישן יותר ממך בלילות הראשונים.', week:9, source:'Mayo Clinic' },
  { id:'w11-teeth', category:'growth', factual_text:'ניצני כל 20 שיני החלב קיימים מתחת לחניכיים כבר בשבוע 11.', aba_line:'20 שיניים מוכנות. עדיין אין לו פה שיכול לנגוס. עוד.', week:11, source:'Mayo Clinic' },
  { id:'w12-urine', category:'growth', factual_text:'מי השפיר מוחלפים כל כמה שעות — הבוטן שותה, מעבד, מפריש.', aba_line:'שותה, משתין, ושותה שוב. לתוך אותו נוזל. זה הנורמל שם.', week:12, source:'ACOG' },
  { id:'w13-gut', category:'growth', factual_text:'המעיים בלטו דרך בסיס חבל הטבור עד שבוע 13 — ואז חזרו פנימה.', aba_line:'המעיים היו בחוץ. הגוף שלח אותם לאחסון זמני. עכשיו חזרו.', week:13, source:"Moore's Embryology" },
  { id:'w14-fingerprints', category:'growth', factual_text:'טביעות האצבע נקבעות בין שבועות 10-16 ולא ישתנו לעולם.', aba_line:'יש לו זהות ביומטרית. Biometric login מגיל 14 שבועות.', week:14, source:'Mayo Clinic' },
  { id:'w15-lanugo', category:'growth', factual_text:'הבוטן מכוסה בשיער עדין (לנוגו) בשבוע 15 — שינשר לפני הלידה.', aba_line:'לרגע קצר הבוטן שלך שעיר לגמרי. ייסתדר.', week:15, source:'Mayo Clinic' },
  { id:'w16-voice', category:'dad', factual_text:'ביום הלידה הדבר הכי מוכר לתינוק יהיה קול האב — אם דיבר אליו.', aba_line:'ביום הלידה הוא לא יכיר כלום. חוץ מהקול שלך. אם דיברת.', week:16, source:'DeCasper & Fifer' },
  { id:'w18-twins-fp', category:'wow', factual_text:'גם תאומים זהים יש להם טביעות אצבע שונות — כי הן מושפעות מסביבת הרחם.', aba_line:'DNA זהה. טביעות שונות. הרחם הוסיף את הפרטים שלו.', week:18, source:'Dermatoglyphics research' },
  { id:'w19-permanent', category:'growth', factual_text:'השיניים הקבועות מתפתחות כבר בשבוע 14-16 — לפני שיצאה שן חלב.', aba_line:'שיניים קבועות: מוכנות. שיניים ראשונות: טרם יצאו. הגוף תמיד קדימה.', week:19, source:'Mayo Clinic' },
  { id:'w20-anatomy', category:'dad', factual_text:'סקירת המחצית בודקת 20+ פרמטרים — מוח, לב, שפתיים, כליות, גפיים.', aba_line:'זה לא "לראות את הבייבי". זה 20+ פרמטרים. תבוא מוכן.', week:20, source:'ACOG, ISUOG' },
  { id:'w23-rem', category:'growth', factual_text:'80% מזמן השינה של הבוטן בשבוע 23 הוא שנת REM — שלב החלומות.', aba_line:'80% שנת חלומות. מה הוא חולם? אנחנו לא יודעים. אבל הוא חולם.', week:23, source:'Fetal sleep research' },
  { id:'w24-pain', category:'growth', factual_text:'הבוטן מסוגל לחוש כאב מגיל 24 שבועות — הוביל לפרוטוקולי הרדמה עוברית.', aba_line:'שבוע 24 — מרגיש כאב. לא תיאוריה. לכן יש הרדמה בניתוחים עובריים.', week:24, source:'Thalamo-cortical connections research' },
  { id:'w25-flavor', category:'wow', factual_text:'מוכח שתינוקות מעדיפים טעמים שהאם אכלה בהריון — מי השפיר משנים טעם.', aba_line:'הוא טועם מה שהיא אוכלת. ויזכור. כשיסרב לאכול — תזכור את זה.', week:25, source:'Flavor learning in utero' },
  { id:'w27-signal', category:'growth', factual_text:'האות ללידה יוצא מריאות הבוטן עצמו — כשהן בשלות מספיק.', aba_line:'הוא מחליט מתי לצאת. הגוף שלו שולח את האות. לא היא.', week:39, source:'Fetal lung maturity research' },
  { id:'w28-eyes', category:'growth', factual_text:'הבוטן פותח עיניים לראשונה בשבוע 26-28 — אחרי 17 שבועות סגורות.', aba_line:'17 שבועות עם עיניים סגורות. שבוע 28 — פתיחה ראשונה.', week:28, source:'Fetal development' },
  { id:'w32-fluid', category:'growth', factual_text:'הבוטן שותה עד 500 מ"ל מי שפיר ביום בטרימסטר השלישי.', aba_line:'500 מ"ל ביום. שותה, מעבד, מפריש. מתרגל לחיים.', week:32, source:'Amniotic fluid research' },
  { id:'gen-placenta', category:'growth', factual_text:'השלייה מייצרת יותר הורמונים מכל בלוטה אחרת בגוף האדם.', aba_line:'השלייה שולטת. יותר הורמונים מכל בלוטה בגוף. לא פלא שהיא מרגישה אחרת.', source:'Placental endocrinology' },
  { id:'gen-blood', category:'bond', factual_text:'נפח הדם שלה עולה ב-50% במהלך ההריון.', aba_line:'פי 1.5 דם בגוף. לא מושאל — מיוצר. ולכן היא עייפה.', source:'ACOG' },
  { id:'gen-heart', category:'bond', factual_text:'הלב שלה עובד 40-50% יותר קשה במהלך ההריון.', aba_line:'הלב שלה עובד 50% יותר קשה. כל יום. 9 חודשים. בלי חדר כושר.', source:'Cardiovascular changes in pregnancy' },
  { id:'gen-brain-mom', category:'bond', factual_text:'המוח שלה מתכווץ קלות במהלך ההריון ומתאושש לאחר הלידה.', aba_line:'המוח שלה קטן קצת בהריון. לא שתגיד לה את זה.', source:'Neurological changes in pregnancy' },
  { id:'gen-smell', category:'dad', factual_text:'חוש הריח מתחזק דרמטית בהריון — תגובת הגנה אבולוציונית לרעלים.', aba_line:'הריח שלה חזק פי כמה. לא גחמה. אבולוציה. תוציא מהבית מה שמסריח.', source:'Olfactory changes in pregnancy' },
  { id:'gen-dna-mom', category:'wow', factual_text:'תאי DNA של הבוטן נשארים בגוף האם עשרות שנים לאחר הלידה.', aba_line:'חלק מהבוטן יישאר בגופה לכל החיים. גם אחרי שיגדל.', source:'Fetal microchimerism research' },
  { id:'gen-cry', category:'growth', factual_text:'תינוקות מתרגלים לבכות ברחם — גלי קול אופייניים נראים בשבוע 28.', aba_line:'הוא מתרגל לבכות. עוד בפנים. יש לו חודשיים חזרות לפני שתשמע.', source:'Gingras et al.' },
  { id:'gen-first-breath', category:'wow', factual_text:'הנשימה הראשונה היא האקט הפיזי המאומץ ביותר שבן אדם אי פעם עושה.', aba_line:'הנשימה הראשונה שלו תהיה הדבר הכי קשה שיעשה אי פעם. ואחרי זה — יגדל.', source:'Neonatal physiology' },
  { id:'gen-recognition', category:'wow', factual_text:'תינוקות מזהים את פני האם תוך שעות מהלידה ומעדיפים לעקוב אחריה.', aba_line:'שעות לאחר הלידה — הוא כבר מעדיף את פניה. חודשים של הכרה בחושך.', source:'Neonatal face recognition' },
  { id:'gen-placenta2', category:'growth', factual_text:'השלייה נבנית כמעט לגמרי מתאי הבוטן — לא מתאי האם.', aba_line:'השלייה נבנית על ידיו. הוא בנה את מכשיר ההזנה שלו בעצמו.', source:'Placental development' },
  { id:'gen-hiccups', category:'growth', factual_text:'שיהוקים עובריים מופיעים מוקדם בהריון — עוד לפני שהריאות מוכנות.', aba_line:'הוא משהק. לפני שיכול לנשום. המוח מתרגל גם בלי אוויר.', source:'Fetal hiccup research' },
  { id:'gen-melatonin', category:'growth', factual_text:'המלטונין של האם עובר לבוטן וקובע לו גרסה ראשונית של שעון ביולוגי.', aba_line:'היא מלמדת אותו יום ולילה. דרך הורמון. בלי מילים.', source:'Circadian rhythm development' },
  { id:'gen-immune', category:'growth', factual_text:'הנבון מקבל נוגדנים מהאם דרך השלייה — רק בטרימסטר השלישי.', aba_line:'החיסונים הראשונים שלו — מגופה. לא מהמזרק. שבועות 28-40.', source:'Passive immunity transfer' },
  { id:'gen-sex', category:'growth', factual_text:'ברירת המחדל הביולוגית היא נקבה — זכר מצריך תוספת של testosterone.', aba_line:'ברירת המחדל הביולוגית היא נקבה. זכר זה תוספת. מעניין.', source:'Sexual differentiation' },
  { id:'gen-folic', category:'dad', factual_text:'חומצה פולית בשבועות הראשונים מפחיתה עד 70% את הסיכון למומי צינור עצבי.', aba_line:'ויטמין אחד, בזמן הנכון, 70% פחות סיכון. תוודא שהיא לוקחת.', source:'ACOG, WHO' },
  { id:'gen-nesting', category:'dad', factual_text:'דחף ה-nesting — לנקות ולסדר לפני הלידה — מוכח הורמונלית.', aba_line:'כשהיא פתאום רוצה לנקות הכל — זה הורמונים. תצטרף. לא תשאל.', source:'Nesting behavior research' },
  { id:'gen-colostrum', category:'bond', factual_text:'הגוף מתחיל לייצר קולוסטרום — החלב הראשון — כבר מסביבות שבוע 16.', aba_line:'החלב הראשון מוכן מחצי הדרך. הגוף שלה לא מחכה לדד-ליין.', source:'Lactation physiology' },
  { id:'gen-dna2', category:'growth', factual_text:'בנבון שנולד יש כ-2 מטר של DNA מקופל לתוך כל תא.', aba_line:'2 מטר DNA בכל תא. מקופל. לתאית. בגוף שלא רואים בלי מיקרוסקופ.', source:'Genomics basics' },
  { id:'gen-contractions', category:'wow', factual_text:'הרחם מתכווץ לאורך כל ההריון — רוב ההתכווצויות לא מורגשות כלל.', aba_line:'הרחם מתכווץ כל הזמן. רק חלק קטן מורגש. שאר הזמן — עבודה שקטה.', source:'Uterine physiology' },
  { id:'gen-twins', category:'wow', factual_text:'תאומים זהים מפתחים אישיות שונה עוד ברחם — מוכח על ידי תנועות שונות.', aba_line:'DNA זהה. אישיות שונה מהרחם. ה-DNA לא קובע הכל.', source:'Twin behavior in utero' },
  { id:'gen-stretch', category:'bond', factual_text:'הרחם גדל מגודל אגרוף לגודל אבטיח — ומתכווץ חזרה לאחר הלידה.', aba_line:'מאגרוף לאבטיח — ואז חזרה. הגוף שלה עושה מה שאף שריר אחר לא יכול.', source:'Uterine physiology' },
  { id:'gen-oxytocin', category:'wow', factual_text:'אוקסיטוצין — "הורמון האהבה" — משתחרר גם בלידה וגם בהנקה.', aba_line:'הורמון שגורם לאהבה משתחרר בלידה. זה לא מטאפורה. זה כימיה.', source:'Oxytocin research' },
  { id:'gen-amniotic', category:'growth', factual_text:'מי השפיר בסוף ההריון מורכבים בעיקר משתן עוברי — לא מנוזל "נקי".', aba_line:'מי השפיר בסוף? בעיקר שתן שלו. הוא שחה בזה. ועכשיו הוא בסדר גמור.', source:'Amniotic fluid composition' },
  { id:'gen-micro', category:'bond', factual_text:'תאים עובריים שעוברים לגוף האם יכולים לסייע בתיקון רקמות פגועות שלה.', aba_line:'הוא לא רק לוקח — הוא גם עוזר לתקן אותה. מהגוף שלו. בלי שיודע.', source:'Fetal microchimerism therapeutic effects' },
  { id:'gen-gravity', category:'bond', factual_text:'הלחץ שהרחם מפעיל על עצב הסיאטיק גורם לכאב שמקרין לרגל — שכיח בT3.', aba_line:'הכאב שלה שיורד לרגל? הבוטן לוחץ על עצב. לא ניתן לתיקון. יחלוף אחרי הלידה.', source:'Sciatic nerve compression in pregnancy' },
  { id:'gen-movement', category:'bond', factual_text:'תנועות עובריות מורגשות ראשית על ידי אמהות מנוסות מוקדם יותר — כי הן מכירות את התחושה.', aba_line:'היא תדע לפני שתוכל להסביר לך מה היא מרגישה. תאמין לה.', source:'Quickening research' },
  { id:'gen-taste2', category:'wow', factual_text:'המחקרים מראים שתינוקות שנחשפו לגזר ברחם מגיבים חיובית לגזר אחרי הלידה.', aba_line:'מה שהיא אוכלת עכשיו — הוא יאהב אחר כך. השקעה לטווח ארוך.', source:'Prenatal flavor learning - carrot study' },
  { id:'gen-brain2', category:'growth', factual_text:'המוח של הנבון ממשיך להתפתח עד גיל 25 — לידה היא רק ציון דרך.', aba_line:'הלידה היא לא הסוף של הפיתוח. עוד 25 שנים. ברוך הבא.', source:'Brain development research' },
  // התפתחות עוברית
  { id:'f051', category:'growth', aba_line:'הבוטן מפהק כבר משבוע 9. לא כי משעמם לו — כי המוח מתרגל רפלקסים.', factual_text:'פיהוקים עובריים מתועדים מסביבות שבוע 9 — חלק מהתפתחות רפלקסים עצביים.', source:'Cleveland Clinic' },
  { id:'f052', category:'growth', aba_line:'יש לו עכשיו שפם. כל הבוטנים עוברים שלב שפם. כולל בנות.', factual_text:'לנוגו — שיער עדין — מכסה את גוף הבוטן מסביבות שבוע 15, כולל אזור הפנים.', source:'Mayo Clinic' },
  { id:'f053', category:'growth', aba_line:'הבוטן שותה מי שפיר ומשתין לתוכם. ושותה שוב. הסדר עובד.', factual_text:'מחזור מי שפיר: הבוטן בולע נוזל ומפריש שתן, המחלופים כל כמה שעות.', source:'ACOG' },
  { id:'f054', category:'growth', aba_line:'המעיים היו בחוץ עד שבוע 12. הגוף אחסן אותם זמנית כי לא היה מקום. עכשיו חזרו.', factual_text:'Physiological umbilical herniation — המעיים יוצאים דרך בסיס חבל הטבור ב-6-10 וחוזרים ב-10-12.', source:"Moore's Embryology" },
  { id:'f055', category:'growth', aba_line:'ברירת המחדל הביולוגית היא נקבה. זכר זה תוספת. מעניין.', factual_text:'מבחינה ביולוגית, ההתפתחות ה"בסיסית" היא נקבה. Y chromosome ו-testosterone מפנים לכיוון זכרי.', source:'ACOG' },
  { id:'f056', category:'growth', aba_line:'הוא כבר מרגיש כאב מסביבות שבוע 24. לא תיאוריה — זו הסיבה שיש הרדמה בניתוחים עובריים.', factual_text:'תלמו-קורטיקלי connections מתפתחים מסביבות שבוע 23-24, מאפשרים עיבוד כאב בסיסי.', source:'ACOG' },
  { id:'f057', category:'wow', aba_line:'כל הריון שהיא עוברת — היא שומרת תאים מהבוטן בגוף שלה. עד עשרות שנים.', factual_text:'Fetal microchimerism: תאי DNA עובריים נמצאו בגוף האם שנים אחרי הלידה.', source:'ACOG' },
  { id:'f058', category:'wow', aba_line:'גם הגוף שלך משתנה. הטסטוסטרון שלך יורד לקראת הלידה. הגוף מכין אותך.', factual_text:'מחקרים מראים ירידה ברמות טסטוסטרון ועלייה בפרולקטין אצל אבות לקראת הלידה.', source:'Hormones and Behavior Journal' },
  { id:'f059', category:'wow', aba_line:'80% מהאבות חווים תסמינים פיזיים של הריון. יש לזה שם: Couvade Syndrome.', factual_text:'Couvade syndrome: בחילות, עייפות ועלייה במשקל אצל אבות. מתועד ב-25-80% לפי מחקרים שונים.', source:'Journal of Reproductive Medicine' },
  { id:'f060', category:'growth', aba_line:'ביום הלידה, מה שהוא יכיר הכי טוב — הקול שלך. אם דיברת.', factual_text:'מחקרים מראים שנבונים מזהים ומגיבים לקולות שנשמעו ברחם, כולל קול האב.', source:'DeCasper & Fifer, Science' },
  // על הגוף שלה
  { id:'f061', category:'bond', aba_line:'הלב שלה עובד 40-50% קשה יותר ממה שהיה לפני ההריון.', factual_text:'נפח הדם של האם עולה ב-40-50% במהלך ההריון, מה שמגביר עומס על הלב.', source:'Mayo Clinic' },
  { id:'f062', category:'bond', aba_line:'הריח שלה חזק פי כמה עכשיו. לא גחמה — אבולוציה. תוציא מהבית מה שמסריח.', factual_text:'שינויים הורמונליים בהריון מגבירים חוש ריח — נחשב הגנה אבולוציונית מרעלים.', source:'Chemical Senses Journal' },
  { id:'f063', category:'bond', aba_line:'המוח שלה משתנה ממש. יש שינויים מבניים שנמשכים שנים אחרי הלידה.', factual_text:'מחקרי MRI הראו שינויים מבניים במוח האם במהלך ההריון שנמשכים לפחות שנתיים.', source:'Nature Neuroscience' },
  { id:'f064', category:'bond', aba_line:'השלייה מייצרת יותר הורמונים מכל בלוטה אחרת בגוף. השלייה שולטת.', factual_text:'השלייה מייצרת estrogen, progesterone, hCG ועוד — יותר מכל איבר אנדוקריני אחר.', source:'Endocrinology Journal' },
  { id:'f065', category:'bond', aba_line:'50% יותר דם בגופה עכשיו. לא מושאל — מיוצר. ולכן היא עייפה.', factual_text:'נפח הדם עולה ב-40-50% בהריון — הלב שואב יותר, הכליות מסננות יותר.', source:'ACOG' },
  // על הלידה
  { id:'f066', category:'growth', aba_line:'4-5% בלבד נולדים בתאריך המשוער. כלומר — EDD הוא הערכה, לא מועד.', factual_text:'רק 4-5% מהנבונים נולדים בתאריך הלידה המשוער. רוב הלידות הן 39-41 שבועות.', source:'ACOG' },
  { id:'f067', category:'growth', aba_line:'האות ללידה יוצא ממנו. הגוף שלו מחליט מתי הוא מוכן.', factual_text:'עדויות מצביעות שאות ללידה מגיע מהריאות העובריות כשהן מבשילות ומפרישות חומר כימי.', source:'Science Translational Medicine' },
  { id:'f068', category:'wow', aba_line:'הנשימה הראשונה שלו ביום הלידה היא האקט הפיזי המאומץ ביותר שיעשה אי פעם.', factual_text:'הנשימה הראשונה דורשת לחץ גדול מאוד לפתיחת שקי האוויר המלאים נוזל.', source:'Neonatal Physiology' },
  { id:'f069', category:'growth', aba_line:'ביום הלידה הוא יזהה את ריח האמא, את קולה ואת פניה. הכל נלמד ברחם.', factual_text:'מחקרים מראים שנבונים מזהים ריח, קול ופנים של האם תוך שעות מהלידה.', source:'Pediatrics Journal' },
  { id:'f070', category:'dad', aba_line:'בשבועיים הראשונים הוא יישן 16-18 שעות ביום. תתרגל לישון בחתיכות.', factual_text:'נבונים ישנים 14-18 שעות ביממה בשבועות הראשונים, ב-2-4 שעות ברצף.', source:'American Academy of Pediatrics' },
  // ישראלי/ספציפי
  { id:'f071', category:'dad', aba_line:'בישראל: 5 ימי לידה לגבר. אפשר להאריך עד 7. תבדוק מול המעסיק מוקדם.', factual_text:'חוק עבודת נשים בישראל מעניק לאב 5 ימי לידה בתשלום. ניתן להאריך.', source:'משרד העבודה הישראלי' },
  { id:'f072', category:'dad', aba_line:'בישראל, כל הבדיקות בהריון מכוסות על ידי קופות החולים. אין עלות ישירה.', factual_text:'בהריון תקין, בדיקות שגרתיות מכוסות על ידי סל הבריאות הישראלי.', source:'משרד הבריאות' },
  { id:'f073', category:'dad', aba_line:'מוקד *5400 פועל 24/7. שאלה רפואית דחופה — שם, לא גוגל.', factual_text:'שירות טלמדיצינה ישראלי: *5400 זמין לייעוץ רפואי כולל נשים בהריון.', source:'משרד הבריאות' },
  // סבב חדש — 30 עובדות נוספות
  { id:'n01', category:'wow', aba_line:'הטסטוסטרון שלך יורד בשליש בהריון. הגוף מכין אותך לאבהות — בלי שביקשת.', factual_text:'רמות טסטוסטרון של אבות יורדות ב-33% במהלך ההריון של בת זוגם.', source:'PMC Longitudinal Paternal Hormones Study' },
  { id:'n02', category:'bond', aba_line:'רק 4% מהאוכל שהיא טורפת הולך לבוטן. ה-96% הנותרים — תחזוקת שרתים פנימיים.', factual_text:'רק 4% מתוספת האנרגיה שהאם צורכת מושקעת ישירות בבניית רקמות העובר.', source:'Duke University Pregnancy Metabolism Study' },
  { id:'n03', category:'bond', aba_line:'היא שוכבת על הספה ולא זזה? הגוף שלה רץ אולטרה-מרתון מטבולי קבוע. תשטוף את הכלים.', factual_text:'גוף האישה בהריון פועל ברמת מאמץ מטבולי של פי 2.2 מהבסיס — גבול פיזיולוגי עליון של גוף האדם.', source:'Duke University / Needed' },
  { id:'n04', category:'dad', aba_line:'הוא שומע אותך עכשיו ויזהה את הקול שלך ביום שיוולד. אם דיברת.', factual_text:'מערכת השמיעה של העובר פעילה מהטרימסטר השני, והוא מסוגל לזהות את תדר הקול הנמוך של האב.', source:'Paternal-Fetal Attachment Research' },
  { id:'n05', category:'dad', aba_line:'בדיקת גנטיקה חינם בקופה מנובמבר 2024. לבדוק אם יש לכם באגים משותפים בקוד.', factual_text:'משרד הבריאות השיק תוכנית בדיקות סקר גנטיות לאומית מורחבת הממומנת במלואה בסל הבריאות.', source:'משרד הבריאות הישראלי' },
  { id:'n06', category:'growth', aba_line:'לשליש מהנשים הבריאות יש GBS. לא מסוכן לה — מחייב עירוי 4 שעות לפני שהראש יוצא.', factual_text:'חיידק GBS נמצא ב-20%-40% מהנשים ההרות הבריאות ללא סימפטומים.', source:'Cleveland Clinic' },
  { id:'n07', category:'growth', aba_line:'שבוע 32 והוא כבר עושה אימוני נשימה עם מי שפיר. מתאמן על הצרחה שתעיר אותך.', factual_text:'סביב שבוע 32 העובר מבצע אימוני נשימה ברחם — שאיבה וכיווץ ריאות עם מי שפיר.', source:'Healthline / Anatomy & Physiology' },
  { id:'n08', category:'growth', aba_line:'לשליש מהתינוקות חבל הטבור כרוך סביב הצוואר בלידה. הוא מקבל חמצן מהחבל — לא מהגרון.', factual_text:'ב-12%-37% מהלידות התינוק נולד עם חבל טבור סביב הצוואר. ברוב המקרים אין סכנה.', source:'Medical News Today / PMC' },
  { id:'n09', category:'bond', aba_line:'אחרי הלידה יש לה צירים חזקים. הרחם סוגר חור בגודל של צלחת שהשאירה השלייה.', factual_text:'לאחר הלידה הרחם מתכווץ בעוצמה כדי לחסום כלי דם פתוחים באתר היפרדות השלייה.', source:'Cleveland Clinic' },
  { id:'n10', category:'bond', aba_line:'שבועיים מהלידה היא תרגיש פתאום מעולה ותנסה לנקות. תעצור אותה — היא עלולה לפתוח מחדש את הרחם.', factual_text:'"אשליית החלמה" — עלייה זמנית באנרגיה שבועיים אחרי הלידה שעלולה להגביר דימום אם לא נחים.', source:'Postpartum Recovery Timeline Study' },
  { id:'n11', category:'bond', aba_line:'הורמון הרלקסין ממיס לה את הרצועות באגן. הסייד אפקט: יציבות של שיכור בבר.', factual_text:'הורמון הרלקסין מרכך רצועות אגן וסחוסים, אך משפיע על כלל רצועות הגוף ופוגע ביציבות.', source:'Cleveland Clinic' },
  { id:'n12', category:'wow', aba_line:'החיבוקים שלך השנה קובעים מתמטית את בריאות הלב שלו בגיל 7. מדע.', factual_text:'מעורבות רגשית ופיזית מוקדמת של האב מנבאת בריאות לב וכלי דם תקינה בגיל 7.', source:'Long-term Paternal Engagement Study' },
  { id:'n13', category:'wow', aba_line:'המוח שלך יתעדכן בשישה שבועות הראשונים כדי לזהות את בכי שלו. אתה מתכנן מחדש.', factual_text:'אבות טריים עוברים שינוי מבני במוח ב-6 שבועות הראשונים שמחדד זיהוי קול התינוק.', source:'Transl Psychiatry / Social Neuroscience' },
  { id:'n14', category:'wow', aba_line:'בחילות בוקר גם אצלך? ברכות — הריון סימפתטי רשמי. יש לזה שם ומחקרים.', factual_text:'Couvade Syndrome: תופעה מוכחת שבה האב חווה בחילות, שינויי תיאבון ועלייה במשקל.', source:'Couvade Syndrome Literature' },
  { id:'n15', category:'growth', aba_line:'הבוטן מחייך מגזר ובוכה מקינואה. הוא מרגיש את הטעם של מה שהיא אוכלת.', factual_text:'העובר מבחין בין טעמים שמועברים דרך תזונת האם למי השפיר ומגיב בהבעות פנים.', source:'Durham University / Taste Development' },
  { id:'n16', category:'growth', aba_line:'שבוע 10 ועיניו היו סגורות מאז שבוע 9. עכשיו פוקח. לא רואה מה אתה עושה. עדיין.', factual_text:'החל משבוע 26 העובר פוקח עיניים וממצמץ, לאחר שהיו סגורות מאז שבוע 9-10.', source:'Mayo Clinic' },
  { id:'n17', category:'growth', aba_line:'שבוע 38 והוא ישן 95% מהזמן. תיהנה מהתמונה — זה הולך להשתנות בצורה קיצונית.', factual_text:'סביב שבוע 38 העובר ישן כ-95% מהזמן במחזורי שינה קבועים.', source:'Cradlewise / Fetal Sleep Physiology' },
  { id:'n18', category:'wow', aba_line:'הפרולקטין שלך עולה ומוריד לך את החשק. הגוף מקדם אותך לאבהות בלי לשאול.', factual_text:'הורמון הפרולקטין עולה אצל גברים במהלך ההריון כדי להגביר התנהגות מגוננת.', source:'Endocrinology of Parenting' },
  { id:'n19', category:'growth', aba_line:'האות ללידה מגיע מהריאות שלו כשהן מוכנות. הוא מחליט מתי לפנות את החדר.', factual_text:'האות הפיזיולוגי הראשי לתחילת הלידה מגיע מהורמונים שמפרישות ריאות העובר הבשלות.', source:'Fetal lung maturity research' },
  { id:'n20', category:'wow', aba_line:'תאי הבוטן יישארו במוח ובלב שלה עשרות שנים. הוא השאיר שם קוד קבוע.', factual_text:'תאי גזע עובריים חוצים את השלייה ונשארים בגוף האם עשרות שנים (מיקרוכימריזם עוברי).', source:'Fetal microchimerism research' },
  { id:'n21', category:'dad', aba_line:'הלחץ שלך מגיע לבוטן דרכה. תהיה הסלע היציב — זה מוריד להם פיזית את מדדי החרדה.', factual_text:'תמיכה רגשית ופיזית של בן הזוג הוכחה כמורידה ישירות את רמות הקורטיזול של האם והעובר.', source:'Endocrinology of Parenting / PubMed' },
  { id:'n22', category:'growth', aba_line:'הלב שלו דופק ב-150 פעימות לדקה. מהיר כפול ממך — כאילו סיים הרגע אינטרוולים.', factual_text:'קצב הלב של העובר עומד על 110-160 פעימות לדקה — כפול מקצב לב מבוגר.', source:'Mayo Clinic' },
  { id:'n23', category:'dad', aba_line:'חיבוק עור לעור שלך בשעה הראשונה מסנכרן את הדופק שלו ומוריד לו את הלחץ בשניות. תעשה את זה.', factual_text:'מגע עור לעור בין האב ליילוד בשעה הראשונה משחרר אוקסיטוצין ומוריד קצב לב ומדדי לחץ.', source:'Systematic Review of Paternal Touch / PMC' },
  { id:'n24', category:'dad', aba_line:'הוא מרגיש את היד שלך על הבטן ויודע שזה לא היא. שים יד. תגיד משהו. חכה.', factual_text:'העובר מרגיש במגע חיצוני החל מהטרימסטר השני ומבצע תנועות תגובה מובחנות.', source:'The Infant Crier / Fetal Competence Research' },
  { id:'n25', category:'dad', aba_line:'1 מתוך 10 אבות חווה דיכאון אחרי לידה. מתבטא בעצבנות ובריחה לעבודה. לא להסתיר.', factual_text:'כ-10% מהגברים חווים דיכאון לאחר לידה, המתבטא לרוב בעצבנות או בריחה לעבודה מוגברת.', source:'PANDA / Medibank' },
  { id:'n26', category:'growth', aba_line:'נפח מי השפיר מגיע לשיא של ליטר בשבוע 32 ומתחיל לרדת. מפנים מקום לגוף שגדל.', factual_text:'נפח מי השפיר מגיע לשיא של כ-1 ליטר בשבוע 32 ומצטמצם לאחר מכן.', source:'Fetal Development Research' },
  { id:'n27', category:'growth', aba_line:'שבוע 36 ועור הבוטן חלק לחלוטין — שיער הגוף העדין נשר לתוך מי השפיר.', factual_text:'שכבת הלנוגו שכיסתה את גוף העובר נשרת כמעט כולה לתוך מי השפיר לקראת הלידה.', source:'Mayo Clinic' },
  { id:'n28', category:'growth', aba_line:'הוא יודע לזחול לכיוון השד מיד אחרי הלידה. רפלקס מולד. לא מדריך הפעלה.', factual_text:'תינוק שמונח על בטן האם מיד אחרי הלידה יודע לזחול באופן עצמאי לכיוון השד.', source:'Fetal Competency Study' },
  { id:'n29', category:'dad', aba_line:'דוקרים אותה קודם לגנטיקה. אם הקוד שלה נקי — אתה פטור מהדקירה אוטומטית.', factual_text:'בבדיקות סקר גנטי קודם נבדק דם האישה. רק אם נמצאה מוטציה — נבדק האב.', source:'משרד הבריאות הישראלי' },
  { id:'n30', category:'growth', aba_line:'מוח העובר מציג שנת REM סדירה בשבוע 28. הוא חולם. מה הוא חולם? אנחנו לא יודעים.', factual_text:'פעילות גלית של שנת חלום (REM) ניתנת לזיהוי רפואי אצל העובר מסביבות שבוע 28.', source:'Purves Neuroscience' },
];
